//
//  MainSceneWorker.swift
//  DemoAssignment
//
//  Created by anurak teerarattananukulchai on 26/9/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import RxAlamofire

class MainSceneWorker {
    let disposeBag = DisposeBag()
    
    func fetchData(request: MainScene.FetchGitHubRepo.Request, _ completion: @escaping (MainScene.GithubRepositoryResult) -> ()) {
        let pageNumber = request.pageNumber
        let url = "https://api.github.com/search/repositories?q=ios&per_page=20&page=\(pageNumber)"
        RxAlamofire.requestData(.get, url)
            .debug()
            .subscribe { (responseServer, data) in
                do {
                    let myItems = try JSONDecoder().decode(MainScene.GithubRepositoryResult.self, from: data)
                    completion(myItems)
                } catch {
                    debugPrint("Error in JSON parsing!")
                }
            }.disposed(by: self.disposeBag)
    }
}
