//
//  MainSceneModels.swift
//  DemoAssignment
//
//  Created by anurak teerarattananukulchai on 26/9/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift


struct MainScene
{
    // MARK: Use cases
    
    struct FetchGitHubRepo {
        struct Request {
            var pageNumber: Int = 1
        }
        
        struct Response {
            let data: MainScene.GithubRepositoryResult?
            let error: Error?
        }
        
        struct ViewModel {
            let data: MainScene.GithubRepositoryResult?
            let error: Error?
        }
        
    }
   
    
    
    // MARK: - GithubRepo
    struct GithubRepositoryResult: Codable {
        let items: [Repository]?
    }
    
    // MARK: - Item
    struct Repository: Codable {
        let id: Int?
        let fullName: String?
        let owner: Owner?
        
        enum CodingKeys: String, CodingKey {
            case id
            case fullName = "full_name"
            case owner
        }
    }
    
    // MARK: - Owner
    struct Owner: Codable {
        let avatarURL: String?
        
        enum CodingKeys: String, CodingKey {
            case avatarURL = "avatar_url"
        }
    }
}



