//
//  MainScenePresenter.swift
//  DemoAssignment
//
//  Created by anurak teerarattananukulchai on 26/9/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainScenePresentationLogic
{
  func presentGithubRepo(response: MainScene.FetchGitHubRepo.Response)
}

class MainScenePresenter: MainScenePresentationLogic
{
  weak var viewController: MainSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentGithubRepo(response: MainScene.FetchGitHubRepo.Response)
  {
      if let error = response.error {
          let viewModel = MainScene.FetchGitHubRepo.ViewModel(data: nil, error: error)
          viewController?.displayGithubRepoFail(viewModel: viewModel)
          return
      }
      
      let viewModel = MainScene.FetchGitHubRepo.ViewModel(data: response.data, error: nil)
      viewController?.displayGithubRepoSuccess(viewModel: viewModel)
  }
}
