//
//  MainSceneInteractor.swift
//  DemoAssignment
//
//  Created by anurak teerarattananukulchai on 26/9/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainSceneBusinessLogic
{
    func fetchData(request: MainScene.FetchGitHubRepo.Request)
}

protocol MainSceneDataStore
{
    //var name: String { get set }
}

class MainSceneInteractor: MainSceneBusinessLogic, MainSceneDataStore {
    var presenter: MainScenePresentationLogic?
    var worker: MainSceneWorker?
    
    // MARK: Do something
    
    func fetchData(request: MainScene.FetchGitHubRepo.Request) {
        worker = MainSceneWorker()
        worker?.fetchData(request: request, { (items) in
            let response = MainScene.FetchGitHubRepo.Response(data: items, error: nil)
            self.presenter?.presentGithubRepo(response: response)
        })
    }
}
